### ISSUE TITLE
About the annotations

### ISSUE THREAD

**Issue by HarborYuan** [kdexd/coco-rem#1]
Hi @kdexd ,

Thank you for your excellent work on the project.

Following the instructions in this repo's README, I visited the project page for the annotations. However, I did not find them on the project page (https://cocorem.xyz). Are these annotations currently available elsewhere?

Kindly @Shweta-singh1 @ydvaayan

**Comment by ydvaayan** [comment]
Hi @HarborYuan ,

The annotations are available on the website's homepage and can be downloaded by clicking 'Download Validation Set' and 'Download Train Set' buttons. The annotations are hosted on google cloud bucket and apparently an issue with that seemed to have caused a problem. The issue seems to have resolved itself. So I would request you to try again and tell us if the problem persists.

Thank You

**Comment by HarborYuan** [comment]
Hi @ydvaayan ,

Thanks for your help. After checking, I found that the problem was with the Safari browser. I tried Chrome again this time, and it works well.
